#ifndef RENDER_CONSOLE_COLOURS_H
#define RENDER_CONSOLE_COLOURS_H

enum RenderConsoleColours
{
	COLOUR_SELECTEDUNIT = 1,
	COLOUR_DAMAGEDUNIT,
	COLOUR_DEADUNIT,
	COLOUR_GRASSTERRAIN,
	COLOUR_DIRTTERRAIN
};

#endif
